= Anatomy of the Go compiler
Damien Lespiau <https://twitter.com/__damien__[@__damien__]>
v0.1
:docinfo1:
:toc: preamble
:icons: font
:hide-uri-scheme:
:source-highlighter: coderay
:quick-uri: http://dlespiau.github.io/go-gc-anatomy/

This article is the results of notes taken while walking through `gc`, the
compiler distributed as part of the https://golang.org/[Go project].

== The basics

=== Quick history

TODO

- go rewrite
- link to video
- SSA

Talk about gccgo/llgo.

=== Invoking the Go compiler

`go build` invokes separate compiler and linker binaries behind the scenes
as shown by the `-x` option:

[source%nowrap,shell]
----
$ go build -x
WORK=/tmp/go-build049312878
mkdir -p $WORK/_/home/damien/src/hello-world/_obj/
mkdir -p $WORK/_/home/damien/src/hello-world/_obj/exe/
cd /home/damien/src/hello-world
$GOROOT/pkg/tool/linux_amd64/compile -o $WORK/_/home/damien/src/hello-world.a -trimpath $WORK -p main -complete -buildid b41aca5027f01d4edf98e1676ee20bd7375510e3 -D _/home/damien/src/hello-world -I $WORK -pack ./main.go
cd .
$GOROOT/pkg/tool/linux_amd64/link -o $WORK/_/home/damien/src/hello-world/_obj/exe/a.out -L $WORK -extld=gcc -buildmode=exe -buildid=b41aca5027f01d4edf98e1676ee20bd7375510e3 $WORK/_/home/damien/src/hello-world.a
cp $WORK/_/home/damien/src/hello-world/_obj/exe/a.out hello-world
----

The Go compiler is really the `compile` tool. The `compile` tool can be
invoked on its own:

[source,shell]
----
$ go tool compile main.go
$ ls main*
main.go  main.o
----

=== Filesystem layout

While to the `go` binary is in `$GOROOT/bin`, tools are located in
`$GOROOT/pkg/tool/$GOOS_$GOARCH`. On Linux with an x86‑64 processor, the
compiler can be found in `$GOROOT/pkg/tool/linux_amd64`.

=== Compiler options

The compiler has quite a few options to play with. Most of them are to
support the integration with `go build`. Some, however, can help
understanding and debugging the compiler itself.

Consider the following Hello World program.

[source,go]
----
package main

func printHelloWorld() {
        println("Hello, World!")
}

func main() {
        printHelloWorld()
}
----

The `-m` option tells us about optimisation decisions the compiler has done.
In this instance `printHelloWorld` can be inlined.

[source,shell]
----
$ go tool compile -m main.go
main.go:3: can inline printHelloWorld
main.go:7: can inline main
main.go:8: inlining call to printHelloWorld
----

NOTE: Compiler options can be passed from `go build` as well with the `-gcflags`
parameter, eg. `go build -gcflags '-m'`.

When applicable, I'll indicate how to get relevant debugging information for
the topic discussed in the rest of this article.

=== Sources

The entry point of the compiler is in @@src/cmd/compile@@ but the bulk of the
code is in various internal packages starting by
@@src/cmd/compile/internal/gc@@. The internal packages are split between
compiler-specific ones in `src/cmd/compile/internal` and some used by several
tools in `src/cmd/internal`. To list a few interesting ones:

@@src/cmd/compile/internal/gc@@:: main package, AST, type checking, inlining,
escape analysis, closure handling, some optimisations and lowering on the AST.

@@src/cmd/compile/internal/syntax@@:: Lexical analysis, tokenization and
building of the first AST representation.

@@src/cmd/compile/internal/ssa@@:: The backend part of the compiler is an
https://en.wikipedia.org/wiki/Static_single_assignment_form[SSA IR] with many
optimisations done at that level.

@@src/cmd/internal/obj@@:: Machine code generation.

== The journey of a go program

=== Overview

1. Initialisation.
2. Lexical analysis and parsing into the `cmd/compile/internal/syntax` AST.
3. Translation into the `cmd/compile/internal/gc` AST.
4. Some gc AST passes: type checking, escape analysis, inlining,
   closure handling, expression evaluation ordering (order.go),
   and some lowering and optimisation (walk.go).
5. Translation into the `cmd/compile/internal/ssa` SSA form.
6. Optimisation and lowering of SSA form.
7. Translation from SSA form to assembler instructions.
8. Translation from assembler instructions to machine code.
9. Writing lots of output: machine code, DWARF symbols,
   type and reflection info, export data

=== Initialisation

The entry point of the compiler is in @@src/cmd/compile/main.go@@ but the
interesting entry point is really @@src/cmd/compile/internal/gc/main.go:Main@@
in the `gc` package.

Various tasks are done there: creating built-in packages like `unsafe`, setting
up the https://golang.org/ref/spec#Blocks[universe block]
(@@src/cmd/compile/internal/gc/universe.go@@), parsing the command line options
and, finally building the https://en.wikipedia.org/wiki/Abstract_syntax_tree[AST]
on which high-level passes are done.

Once the files are parsed, the global variable
@@src/cmd/compile/internal/gc/go.go:xtop@@ contains the list of top level `Nodes`.

NOTE: There are actually two different AST. One in the
@@src/cmd/compile/internal/syntax@@ package and one in the
@@src/cmd/compile/internal/gc@@ package. The former is transformed into the
latter right at the start (in @@src/cmd/compile/internal/gc/noder.go@@,
@@src/cmd/compile/internal/gc/noder.go:parseFiles@@). It seems there's a will
to get rid of the `gc` AST in favour of the `syntax` one
(https://go-review.googlesource.com/c/40693/[source]).

Of course, the reference to have handy when looking at the parsing code is the
https://golang.org/ref/spec[The Go Programming Language Specification].

=== Inlining

https://en.wikipedia.org/wiki/Inline_expansion[Inlining] is quite an important
optimisation. Not only it removes some function call overhead but, more
importantly, it enables further function-wide optimisations at a later stage.

The inlining code is in @@src/cmd/compile/internal/gc/inl.go@@ with a nice
explanatory comment at the top of the file. A first pass in
@@src/cmd/compile/internal/gc/inl.go:caninl@@ decides which functions can be
inlined. A second pass, @@src/cmd/compile/internal/gc/inl.go:inlcalls@@, will
expand inlinable functions at their call sites.

@@src/cmd/compile/internal/gc/inl.go:ishairylist@@ and
@@src/cmd/compile/internal/gc/inl.go:ishairy@@  walk the function and decide if
it's too _hairy_ (ie. complex) to be inlined or not with a budget of 80 AST
nodes.

The Go compiler can inline across package boundaries.

The inliner only inlines leaf functions (with
https://github.com/golang/go/commit/77ccb16eb12f461eaea5fdf652a2e929dc154192[some exceptions^]).
https://github.com/golang/proposal/blob/master/design/19348-midstack-inlining.md[Mid-stack
inlining^] is in the pipeline.

The `-m` flag can be used to see the inliner in action:

[source,go]
----
include::inlining/inlined/inlined.go[]
----

[source,shell]
----
$ go tool compile -m inlined.go
include::inlining/inlined/inlined.output[]
----

The undocumented option `-m=2` gives more insights into the reasons the
compiler doesn't inline certain functions.

[source,go]
----
$ cat not-inlined.go
include::inlining/not-inlined/not-inlined.go[]
----

[source,shell]
----
$ go tool compile -m=2 not-inlined.go
include::inlining/not-inlined/not-inlined.output[]
----

=== Escape Analysis

TODO

=== SSA

TODO

== Interaction with the runtime

=== Growing stacks

TODO

== Chosen pieces

=== Go calling convention

TODO

=== Go assembler

TODO
